name: My-GitHubActions
env:
 APPLICATION_NAME: "MyFlask"
 DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha}}"
 
on:
  push:
   branches: 
     - main

jobs:
  my_testing:
   runs-on: ubuntu-latest
   steps:
     - name: Print Hello Message in Testing
       run: echo "Hello World from Testing job"
       
     - name: Execute few coomands
       run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name:  ${{ env. APPLICATION_NAME }}"
        
     - name: List current folder
       run: ls -la

     - name: Git clone my repo
       uses: actions/checkout@v1

     - name: List current folder
       run: ls -la

  my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   env:
    VAR1: "This is job Level Variable1"
    VAR2: 2
    
   steps:
     - name: Print Hello Message in Deploy
       run: echo "Hello World from Deploy job"
       
     - name: Printing Deployment package
       run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

     - name: Check AWS
       run: aws --version

     - name: Check ZIP
       run: zip

     - name: Print VAR
       run: "${{ env.VAR1 }} = ${{ env.VAR2 }}"
       
  

   
    
   
   
     
   
